SET SERVEROUTPUT ON


--DECLARE
--      CURSOR C1 IS SELECT * FROM EMP
--      WHERE DEPTNO=10 FOR UPDATE OF SAL NOWAIT;
--     BEGIN
--      FOR I IN C1 LOOP
--        UPDATE EMP SET SAL=1500+I.SAL WHERE CURRENT OF C1;
--        
--      END LOOP;
--      DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT);
--     END;


--DECLARE
----DECLARE CURSOR
--     CURSOR C1 IS SELECT * FROM EMP;
------DECLARE RECORD
--     EI C1%ROWTYPE;
--    BEGIN
--     OPEN C1;
--     LOOP
--     
--      FETCH C1 INTO EI;
--      EXIT WHEN C1%NOTFOUND;
--      DBMS_OUTPUT.PUT_LINE(EI.EMPNO||' '||EI.ENAME||' '||EI.SAL||' '||EI.HIREDATE||' '||EI.DEPTNO);
--    END LOOP;
--    CLOSE C1;
--   END;

--DECLARE
--    JOB_ID VARCHAR2(20):=UPPER('&DESIGNATION');
----    INCR_AMT NUMBER:=&INCREAMENTAL_AMOUNT;
--    BEGIN
--     delete from EMP
--     WHERE UPPER(JOB)=JOB_ID;
--     IF SQL%ROWCOUNT>0 THEN
--      DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT||' RECORDS DELETED AGAINST THE DESIGNATION '||JOB_ID);
--    ELSE
--     DBMS_OUTPUT.PUT_LINE('INVALID DESIGNATION, RECORDS NOT FOUND...');
--    END IF;
--   END;

--SELECT * FROM EMP;